package com.popovych.networking.enumerations;

public enum MessageType {
    NONE,
    CLIENT_SERVERS_QUERY,
    DATABASE_SERVERS_RESPONSE,
    SERVER_INSERT_QUERY,
    SERVER_DELETE_QUERY,
    GAME_CLIENT_REGISTER,
    GAME_CLIENT_SYNC,
    GAME_CLIENT_WAIT,
    GAME_CLIENT_UNREGISTER,
    GAME_SERVER_ACCEPTED,
    GAME_SERVER_DENIED,
    GAME_SERVER_SIGNAL,
    GAME_SERVER_SYNC,
    GAME_SERVER_STOP
}
